### ISSUE TITLE
repetition behaviour not working correctly

### ISSUE THREAD

**Issue by biokomiker** [bassmanitram/actions-for-nautilus#17]
Dear Martin,

reading carefully your manual I wanted to take the advantage of the repetition behaviour with SINGULAR placeholders.  The command (echo %f) appears to be repeated but repeatedly on the first entry. That is what I understand from the output:

`COMMAND 0
['echo', '/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27']

COMMAND 1
['echo', '/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27']
/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27

COMMAND 2
['echo', '/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27']
/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27
/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27

COMMAND 3
['echo', '/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27']

COMMAND 4
['echo', '/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27']
/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27

COMMAND 5
['echo', '/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27']
/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27
/home/georg/Bilder/Bilder (_home-hd_)/import/Sony RX-100M3/2022/2022-08-27
`

The behaviour is the same with %d, %f and %b.

**Comment by bassmanitram** [comment]
Hey. Ok I'll take a look... Thx for the report

**Comment by bassmanitram** [comment]
Lol - so it turns out that only `%f` amongst the SINGULAR placeholders had the bug in it, but the behaviour of some of the ANY placeholders was also not as described.

Testing the fix now

**Comment by bassmanitram** [comment]
Tests work, PR created https://github.com/bassmanitram/actions-for-nautilus/pull/18

Once merged this will form part of release 1.3 (later today, I'm hoping)

**Comment by bassmanitram** [comment]
Released as part of v1.3.0

**Comment by biokomiker** [comment]
Installed via deb, works like a charm - Thanks!

**Comment by bassmanitram** [comment]
> Installed via deb, works like a charm - Thanks!

NP.
