### ISSUE TITLE
How to move menu entries to the top?

### ISSUE THREAD

**Issue by hamad12a** [bassmanitram/actions-for-nautilus#27]
How to popular the context menu options; say I added this context menu "Open in VS Code" I want to move to the top of the context menu, it should be the first appears before the "Open" option.

**Comment by bassmanitram** [comment]
For a submenu:
 
* Select the submenu
* Set its sort mode to "manual" (you'll need to "activate" that option too)

![image](https://user-images.githubusercontent.com/12625370/199299340-9b112344-509a-4af4-ada9-0d1c8002649c.png)

* Select the item in **Submenu Actions**
* Use the arrows next to the next to the action type (*Command* in the image below) to move the item up/down

![image](https://user-images.githubusercontent.com/12625370/199299985-f0d68b80-8819-4109-af0e-c56d1d9a1655.png)

**Comment by hamad12a** [comment]
But this method does not allow moving the option to the top of the context menu

**Comment by bassmanitram** [comment]
Then that's a big! I'll check it

**Comment by bassmanitram** [comment]
Indeed, for submenus this does not work - hopefully I'll get a fix issued today

**Comment by bassmanitram** [comment]
Fixed in [Release 1.5.1](https://github.com/bassmanitram/actions-for-nautilus/releases/tag/v1.5.1)

**Comment by hamad12a** [comment]
@bassmanitram Not sure if you understood my issue

**Comment by bassmanitram** [comment]
If you want the entries at the very top of the context menu, I don't think
that's possible
