### ISSUE TITLE
Update to support nautilus-python v4

### ISSUE THREAD

**Issue by bassmanitram** [bassmanitram/actions-for-nautilus#31]
https://gnome.pages.gitlab.gnome.org/nautilus-python/nautilus-python-migrating-to-4.html

**Comment by markd89** [comment]
I'm running Bookworm and can test when you're ready, thanks!

**Comment by bassmanitram** [comment]
> I'm running Bookworm and can test when you're ready, thanks!

Hey there. Thanks, that would be very helpful! I THINK it's ready for initial testing now. If you clone the repo, checkout the nautilus-python-4-prep branch, and install from the command line as described in the README then you'll have the current state of the mods installed. Then just report back all the errors you get :)

Make sure you remove your current installation before doing the above - this won't destroy your config.

When reporting back, can you do so with comments on the [PR](https://github.com/bassmanitram/actions-for-nautilus/pull/32) rather than here. Thanks

**Comment by markd89** [comment]
Hi, thanks, forgive my ignorance.

I know how to git clone the repo. i.e. git clone https://github.com/bassmanitram/actions-for-nautilus

How do I "checkout the nautilus-python-4-prep branch"? 

Thanks,
Mark

**Comment by bassmanitram** [comment]
> Hi, thanks, forgive my ignorance. I know how to git clone the repo. i.e. git clone https://github.com/bassmanitram/actions-for-nautilus How do I "checkout the nautilus-python-4-prep branch"? Thanks, Mark
> 

Hey - after you have done the clone, cd into the directory into which you cloned the repo and execute the command...

```
git switch nautilus-python-4-prep
```

then just do the rest of the manual installation process from there.
