### ISSUE TITLE
Configurator startup is not working with palemoon

### ISSUE THREAD

**Issue by bassmanitram** [bassmanitram/actions-for-nautilus#34]
From @markd89

> One minor thing and I think this is my system.. but in the configurator I had to change:
> 
> xdg-open http://localhost:$PORT # >> /tmp/a4n-start.log
> 
> to
> 
> firefox http://localhost:$PORT # >> /tmp/a4n-start.log
> 
> Palemoon is my default browser and didn't like something there.

**Comment by bassmanitram** [comment]
Hey @markd89

I installed pale moon, set it as my default browser, and started the configurator. All went well for me. Can you give me more details about what is going wrong for you?

For example, restore the script to use `xdg-open`, then, in a terminal run the following

```
cd $HOME/.local/share/actions-for-nautilus-configurator
./start-configurator.sh
```

Attach any error messages/output to this issue.

Thanks

**Comment by markd89** [comment]
Thanks for your patience @bassmanitram I just got back from a trip.

Yes, I think this is may be a peculiarity issue on my system.

I edited the script to see the errors:
```
# Start web page
#
xdg-open http://localhost:$PORT 
```

`mark@[machinename]:~$ cd $HOME/.local/share/actions-for-nautilus-configurator
bash: cd: /home/mark/.local/share/actions-for-nautilus-configurator: No such file or directory
`

the script is in a different directory, I'm not sure why but that seems to be why it fails:

```
mark@[machinename]:~$ /usr/share/actions-for-nautilus-configurator/start-configurator.sh
python3: can't open file '/home/mark/./find-a-port.py': [Errno 2] No such file or directory
python3: can't open file '/home/mark/./actions-for-nautilus-configurator.py': [Errno 2] No such file or directory
```

If it's working for you on a normal install maybe we shouldn't worry about this one?

**Comment by bassmanitram** [comment]
I can make that work if I can do so without any hard dependencies on BASH itself.
