### ISSUE TITLE
Add "Open in VS Code" to Wiki

### ISSUE THREAD

**Issue by Lukas-Schillinger** [bassmanitram/actions-for-nautilus#40]
Hello, 

I'd like to contribute an "Open in VS Code" configuration to the project wiki. This is not an issue but Github doesn't support pull requests for wikis. 

Looking at a [google search for adding "Open in VS Code" to the context menu](https://www.google.com/search?q=Add+open+with+vscode+to+context+menu+in+Ubuntu&sourceid=chrome&ie=UTF-8) this is a fairly sought after feature. 

The following configuration has worked for me on Ubuntu 22.04 and 22.10

```
, {
    "type": "command",
    "label": "Open in VS Code",
    "command_line": "code --new-window %f",
    "filetypes": [
        "directory", 
        "file"
    ]
}
```

**Comment by bassmanitram** [comment]
Lovely - added to the Wiki! Thanks for the contribution
