### ISSUE TITLE
The Configuration UI is open to all

### ISSUE THREAD

**Issue by rahulhaque** [bassmanitram/actions-for-nautilus#41]
The json configuration web portal can be accessed by anyone connected to the same network if he/she knows the port number it is running on. Is it possible to close the server from the UI or any other way?

**Comment by bassmanitram** [comment]
When you close the tab, the server SHOULD close. If you are not seeing that
then I need to address it.

I had intended to only open on the localhost interface! That appears NOT to
be the case, for which I sincerely apologise. I'll produce an emergency
patch to fix that! ROOKIE mistake!

I can also try to secure the Comms and access by other means, which will
take a bit longer to research!

Thanks for the report.

Martin Bartlett

**Comment by rahulhaque** [comment]
> When you close the tab, the server SHOULD close. If you are not seeing that
then I need to address it.

Yes, after closing the tab, the server still running in the background. I am on PopOS 22.04.

> I had intended to only open on the localhost interface! That appears NOT to
be the case, for which I sincerely apologise. I'll produce an emergency
patch to fix that! ROOKIE mistake!

No worries, take your time.

Waiting eagerly for the next update. IMHO you can try to make the configuration editor offline to serve as a html file. Then open that html file in the browser instead of running a new server. BTW thank you for this.

**Comment by bassmanitram** [comment]
@rahulhaque - the referenced PR fixes it. Any chance you can test too? (I'll prep the release)

**Comment by bassmanitram** [comment]
> > When you close the tab, the server SHOULD close. If you are not seeing that
> > then I need to address it.
> 
> Yes, after closing the tab, the server still running in the background. I am on PopOS 22.04.
> 
> > I had intended to only open on the localhost interface! That appears NOT to
> > be the case, for which I sincerely apologise. I'll produce an emergency
> > patch to fix that! ROOKIE mistake!
> 
> No worries, take your time.
> 
> Waiting eagerly for the next update. IMHO you can try to make the configuration editor offline to serve as a html file. Then open that html file in the browser instead of running a new server. BTW thank you for this.

Can you tell me what browser you are using - I too am on PopOS 22.04, I'm using Chrome

**Comment by bassmanitram** [comment]
Arghgh - indeed, under Firefox it is NOT closing! Looking into it

**Comment by bassmanitram** [comment]
Lates commit in the PR fixes that

**Comment by bassmanitram** [comment]
Actually, because of the seriousness, I'm going to merge the PR to master and prep the release.

**Comment by rahulhaque** [comment]
I am running Brave Browser. Which I guess equivalent to Chrome.

**Comment by rahulhaque** [comment]
@bassmanitram I've tested in brave browser and it is working fine. The port is also listening to only 127.0.0.1. Time to release a new version and update the .deb packages. Thank you.

**Comment by bassmanitram** [comment]
Excellent thx - release is prepped and should be there in a few moments.

Thanks for the report and sorry for the very embarrassing error!

**Comment by rahulhaque** [comment]
No worries, happens to all of us. Take care. 🙂
