### ISSUE TITLE
Certain commands don't seem to work with zenity

### ISSUE THREAD

**Issue by D10f** [bassmanitram/actions-for-nautilus#44]
Hi, I've been playing around with this amazing program for the past few hours trying to understand how it works and hopefully come up with useful quick actions for my context menu. In doing so I found that certain commands that run fine in the terminal, won't work when used as a command for Actions For Nautilus. For example:

```
du -sh ~/Downloads | xargs -I {} zenity --info --text={} --width 150
```
This command creates a new dialog window using zenity displaying the output of the `du` command. When translated to AFN however, it doesn't seem to do anything.

```
du -sh %d | xargs -I {} zenity --info --text={} --width 150
```
I've tried several combinations of placeholders such as `%D` or `%F`, as well as alternative ways to capture the output of the command to feed into zenity (quoting the placeholder, specifying the current working directory, etc).
I've also enabled debugging output but again there's no output to be seen anywhere, even after running Nautilus from the terminal.

Here's the JSON produced by this action rule as described:

```json
{
   "type": "command",
   "label": "Calculate total size",
   "command_line": "du -sh %D | xargs -I {} zenity --info --text={} --height 150",
   "filetypes": [
     "directory"
   ]
},
```

As a side note (I can create another issue if you want), I think it would be extremely useful to have a button to force the updated configuration to take place rather than waiting for 30 seconds.

Thanks!

**Comment by bassmanitram** [comment]
Hey, sorry I didn't get back to you before you resolved it. Glad you
managed to figure it out. The "waiting 30 seconds" thing is actually
because it's quite difficult to get the extension itself to respond to file
change or other asynchronous notifications - the only way I've found that
works at the moment is a timer event - hence the 30 seconds. I'll keep
looking though.
