### ISSUE TITLE
Not working on Ubuntu 22.10

### ISSUE THREAD

**Issue by threed-factory-store** [bassmanitram/actions-for-nautilus#45]
Followed the install instructions:
- Downloaded and installed the deb
- Ran Actions for Nautilus Configurator
- Added my command
- Restarted Nautilus

I don't see any commands in the right-click menu of an image file.

**Comment by bassmanitram** [comment]
Hey there. Can you attach your configuration file (the doc tells you where
to find that)

Thanks

**Comment by bassmanitram** [comment]
I have installed the extension on a fresh Ubuntu 22.10 installation and it seems to work in general. A reminder of the installation process:

* Download and install the deb 
* Alt-F2 (or open a terminal)
* `nautilus -q`

This will install the deb and restart Nautilus in order to immediately see the extension.

You should then:

* Open the configurator - this will install the default/demo config for the user
* After about 30 seconds, open nautilus and right click on a folder - you should see something like this
   ![image](https://user-images.githubusercontent.com/12625370/232210371-c12b1a49-f730-4242-987f-9de231b81270.png)
   Note the three items at the bottom (before `Open in Terminal` and `Properties`) which are added by the extension.

You can then be sure that extension is installed and working (I am working on an alternative and cleaner approach to configuration update in Nautilus rather than the timer, but it's actually tougher than it seems :))

After that, the non-appearance of certain actions for certain files is almost certainly because the action hasn't been correctly configured.

However, having your configuration would allow me to confirm this in your particular use case.

**Comment by bassmanitram** [comment]
@threed-factory-store - do you have any more help for me in addressing this?

**Comment by threed-factory-store** [comment]
This is so bizarre.  I've responded to your emails, but my responses are not showing up here.  So here goes:

It looks to me like it's not installed properly.  Here's my config file and a screen shot of the right-click menu for an image file.  The item I've added is to send an image to my blog.  It's a bash script which works fine if I run it by itself.

![RightClickMenu](https://user-images.githubusercontent.com/79147271/233781772-b7544cc2-d84b-444b-ad2f-0f7a79d97cae.png)

Here's my config file:

{"actions": [{"type": "command", "label": "Run in python3", "command_line": "gnome-terminal -t \"Running Python %b\" --profile \"No Close\" -- python3 %b", "cwd": "%d", "max_items": 1, "mimetypes": ["text/x-python"]}, {"type": "command", "label": "Test all place holders", "command_line": "%O printf '%%s\\n' '#b' %b '#B' %B '#c' %c '#d' %d '#D' %D '#f' %f '#F' %F '#h' %h '#m' %m '#M' %M '#n' %n '#o' %o '#O' %O '#p' %p '#s' %s '#u' %u '#U' %U '#w' %w '#W' %W '#x' %x '#X' %X | zenity --title \"Test all place holders\" --text-info", "use_shell": true}, {"type": "command", "label": "Open in gedit", "command_line": "gedit %F", "filetypes": ["!directory", "standard"]}, {"type": "menu", "label": "Folder Actions", "actions": [{"type": "command", "label": "Execute command here", "command_line": "$(zenity --entry --text \"Enter command\" --title \"execute command in %f\" --width 800)", "cwd": "%f", "use_shell": true, "max_items": 1, "filetypes": ["directory"]}, {"type": "command", "label": "Start HTTP server here", "command_line": "gnome-terminal -t \"HTTP Server on %f\" -- python3 -m http.server --bind 127.0.0.1", "cwd": "%f", "max_items": 1, "mimetypes": ["inode/directory"]}]}, {"type": "menu", "label": "Copy details", "actions": [{"type": "command", "label": "Copy name", "command_line": "echo -n %B | xclip -f -selection primary | xclip -selection clipboard", "use_shell": true}, {"type": "command", "label": "Copy path", "command_line": "echo -n %F | xclip -f -selection primary | xclip -selection clipboard", "use_shell": true}, {"type": "command", "label": "Copy URI", "command_line": "echo -n %U | xclip -f -selection primary | xclip -selection clipboard", "use_shell": true}]}, {"type": "command", "label": "Send To Blog", "command_line": "ImageToBlog \"%F\"", "use_shell": true, "min_items": 1, "max_items": 1, "permissions": "read"}]}

**Comment by threed-factory-store** [comment]
After it's installed, where is the app that shows the right-click menu, and how does it get run?

**Comment by bassmanitram** [comment]
The main extension goes in `/usr/share//nautilus-python/extensions/actions-for-nautilus`, whereas the configurator goes in `/usr/share/actions-for-nautilus-configurator`. See [the makefile](https://github.com/bassmanitram/actions-for-nautilus/blob/main/Makefile) for more info.

**Comment by threed-factory-store** [comment]
Had some time before I had to leave....
    pip install PyGObject
gave me some errors which led me to...
    sudo apt install pkg-config
after which I tried installing PyGObject again which gave me...
        ....    
        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-310
            creating build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'cairo' found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]

I don't know what's going on.

**Comment by bassmanitram** [comment]
Been searchin'. 

{{gi}} should be here - {{/usr/lib/python3/dist-packages/gi}} - get that out of the way first

If so, then I _think_ for some reason python3 itself isn't configured to _look_ there for the module...

**Comment by bassmanitram** [comment]
Do you have a hard setting of `PKG_CONFIG_PATH` in your shell environment? That's just a guess, by the way.

**Comment by threed-factory-store** [comment]
Hey, hey, hey!  That was it!   

My sys.path didn't list any dist-packages folders.  I added /usr/lib/python3/dist-packages and now I see the menu items.  Time to add mine and make the magic happen.  

Thanks for diagnosing my Python problems Martin!

**Comment by bassmanitram** [comment]
> Hey, hey, hey! That was it!
> 
> My sys.path didn't list any dist-packages folders. I added /usr/lib/python3/dist-packages and now I see the menu items. Time to add mine and make the magic happen.
> 
> Thanks for diagnosing my Python problems Martin!

No problem. Glad to help
