### ISSUE TITLE
Open a terminal as root in a specific folder

### ISSUE THREAD

**Issue by zz0rk** [bassmanitram/actions-for-nautilus#47]
This doesn't seem to work properly on Debian 11, Gnome 43.6, Wayland.
The elevated prompt authentication window prompt comes up but after entering the credentials the terminal won't open.

**Comment by bassmanitram** [comment]
You are right - running it from a terminal gives...

# Error constructing proxy for
org.gnome.Terminal:/org/gnome/Terminal/Factory0: Failed to execute child
process “dbus-launch” (No such file or directory)

Wayland, apparently, fulfills SOME DBus needs and so DBus doesn't get
installed by default (see here for the lowdown -
https://blogs.kde.org/2020/10/11/linux-desktop-shell-ipc-wayland-vs-d-bus-and-lack-agreement-when-use-them
).

Anyway, you can make this work by installing dbus-x11.

I'll add this to the Wiki.

Thanks for using actions-for-nautilus

**Comment by zz0rk** [comment]
Bingo
Switching from Debian 11 to Debian 12 was such let down as far as Nautilus is concerned. Your actions add excellent value to extend its usability. Thank you for that!

**Comment by zz0rk** [comment]
Bingo
Switching from Debian 11 to Debian 12 was such let down as far as Nautilus is concerned. Your actions add great value to extend its usability. Thank you for that!
