### ISSUE TITLE
how can I see the debug output？

### ISSUE THREAD

**Issue by kagg886** [bassmanitram/actions-for-nautilus#50]
I want to zip a file by using 7zip, here is my shell:
```shell
a="%F"; 7z a -si -bd -tzip "newZip.zip" <<< "$(echo -n "$a" | tr '\n' ' ')"
```
but it not works, so i want to see the debug output.

can you tell me how can I get the nautilus `stdout` :(

**Comment by bassmanitram** [comment]
Ooops - sorry @kagg886 - missed this.

[This part of the readme should help](https://github.com/bassmanitram/actions-for-nautilus?tab=readme-ov-file#diagnostics)

**Comment by bassmanitram** [comment]
@kagg886 - did that help? Can I close?

**Comment by kagg886** [comment]
i resolve it thanks :D
