### ISSUE TITLE
not an issue, for the Wiki

### ISSUE THREAD

**Issue by biokomiker** [bassmanitram/actions-for-nautilus#52]
to compress pdf via gs

        {
            "type": "command",
            "label": "compress pdf",
            "command_line": "gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET -dBATCH -dAutoRotatePages=/None  -dPDFSETTINGS=/ebook -r100 -sOutputFile=%w\"_compressed.pdf\"  %b",
            "cwd": "%d",
            "mimetypes": [
                "application/pdf"
            ],
            "filetypes": [
                "standard"
            ]
        },

-r sets the resolution and has a strong effect on file size; you may also delete -r in this case the file size is strongly effected by
-dPDFSETTINGS=/ebook if you set this to -dPDFSETTINGS=/screen you get tiny pdfs with very low resolution

Thanks again for this nice tool & Merry Xmas

**Comment by bassmanitram** [comment]
VERY cool! Adding it immediately. Thanks for using the tool and merry christmas/happy new year to you too!
