### ISSUE TITLE
Static port for web interface

### ISSUE THREAD

**Issue by Batwam** [bassmanitram/actions-for-nautilus#58]
Hello,

I am not sure if I am using the right terminology, but I noticed as I tried to bookmark the web interface for easy access in my web browser that the "port" being used seems to change every time the app is being started. Would there be a way for this port to be fixed to allow bookmark, either by default or as an option in the interface where the user can specify the port to be used?
![image](https://github.com/bassmanitram/actions-for-nautilus/assets/56710655/4c413449-591d-43bf-aad0-242ffc1a58af)

I'm guessing this would require some update in [this file](configurator/find-a-port.py) and probably a restart of nautilus to take the change into account. If ports with lower numbers are likely to be taken, perhaps limit the ports to being 10000+ or even higher number to minimise the risk of this being already being taken?

**Comment by bassmanitram** [comment]
Hey there - yes the terminology is right. The problem with the bookmark is
that each time you start the app you (re)start the server - so it's on an
arbitrary port - and when you close the browser tab the server closes too.
So a bookmark won't be of any use, I'm afraid

**Comment by Batwam** [comment]
Thanks for the quick response. This issue can be closed 👍
