### ISSUE TITLE
Blank page when starting AFN

### ISSUE THREAD

**Issue by Creteil** [bassmanitram/actions-for-nautilus#59]
I have strange behavior on one computer.

If I open the link inside terminal, except from the fact I can't render properly,  I can see AFN answering and serving the content :
```bash
root@oem-ThinkPad-P15-Gen-1:~# lynx -dump http://localhost:60125
   IFRAME: [1]/actions-for-nautilus-configurator.html

   IFRAME: [2]/actions-for-nautilus-configurator-help.html

Références

   1. http://localhost:60125/actions-for-nautilus-configurator.html
   2. http://localhost:60125/actions-for-nautilus-configurator-help.html
root@oem-ThinkPad-P15-Gen-1:~#
```
But the link doesn't render at all inside browser :

![image](https://github.com/bassmanitram/actions-for-nautilus/assets/27310214/64eaab50-737a-4665-a464-cdbfc2a30078)

**Comment by bassmanitram** [comment]
Bizarre! What's the browser?

**Comment by Creteil** [comment]
```bash
oem@oem-ThinkPad-P15-Gen-1:~$ dpkg -l | grep firefox
ii  firefox                                          122.0.1+build1-0ubuntu0.22.04.1~mt1                        amd64        Safe and easy web browser from Mozilla
ii  firefox-locale-en                                122.0.1+build1-0ubuntu0.22.04.1~mt1                        amd64        English language pack for Firefox
ii  firefox-locale-fr                                122.0.1+build1-0ubuntu0.22.04.1~mt1                        amd64        French language pack for Firefox
oem@oem-ThinkPad-P15-Gen-1:~$
```

**Comment by bassmanitram** [comment]
That version FF "works here" :)

Try the F12 key - that brings up the developer tools. Then click on
"console" and see if you have any error messages

**Comment by Creteil** [comment]
There is 2 Warning :

![image](https://github.com/bassmanitram/actions-for-nautilus/assets/27310214/b6de4f6e-05b7-4691-b39f-c0b87959cec0)

They respectively send to explanation :

- [Quirks Mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)
- [Partitioned: All third-party storage access requests - Privacy on the web](https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_access_policy/Errors/CookiePartitionedForeign)

**Comment by Creteil** [comment]
The good news is that on the other computer where everything work properly, these 2 warning doesn't exist :

![image](https://github.com/bassmanitram/actions-for-nautilus/assets/27310214/2ac00dac-e019-4d53-b832-adcf99ab54d4)

**Comment by Creteil** [comment]
There is 2 Warning :

![image](https://github.com/bassmanitram/actions-for-nautilus/assets/27310214/b6de4f6e-05b7-4691-b39f-c0b87959cec0)

They respectively send to explanation :

- [Quirks Mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)
- [Partitioned: All third-party storage access requests - Privacy on the web](https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_access_policy/Errors/CookiePartitionedForeign)

**Comment by Creteil** [comment]
Found the culprit !!!

This is « ESET Endpoint Antivirus » that avoid all the browser's to connect as « http » to « localhost ».

You can close the ticket, I will have to find the way to put exclusion on this behavior...

**Comment by bassmanitram** [comment]
Can you check if the suggestion made relating to cookie partitioning makes
it work?

**Comment by Creteil** [comment]
Yes checked this suggestion but it nothing changed, this is due to the « ESET Endpoint Antivirus » on the host.

I have set an exclusion in the « ESET PROTECT Cloud console » and everything work smooth since that... 👍

**Comment by bassmanitram** [comment]
Ah ok. Glad it's working now
