### ISSUE TITLE
Web UI not saving config edits

### ISSUE THREAD

**Issue by Lukas-Schillinger** [bassmanitram/actions-for-nautilus#9]
Hello, 
Today I installed the most recent version of actions-for-nautilus on a new machine and saw that none of the changes made in the web interface save to the config.json file. 

### Install Steps
`sudo apt install python3-nautilus python3-gi procps`
`git clone git clone https://github.com/bassmanitram/actions-for-nautilus.git`
`cd actions-for-nautilus`
`make install`
After this I did a full reboot
Both the `actions-for-nautilus` and `actions-for-nautilus-configurator` are present in my `Home/local/share/` directory 

### Steps to Reproduce Issue
'nautilus-actions-configurator' web interface launched from from 'applications' shortcut
No changes made to the configuration are actually saved after saving. I tried editing names, deleting commands, and adding new commands. Running `nautilus -q` and `sudo reboot` after saving changes did not work. 

Manually editing the `config.json` still works

### System Specs
Ubunut 22.04.1
GNOME nautilus 42.2

**Comment by bassmanitram** [comment]
Hey Lukas, I'm unable to recreate your problem at all (I uninstalled everything and then did a local make install as you did).

Can you do the following:

* Alt-F2 then `nautilus -q`
* from a terminal enter `nautilus --no-desktop`

Then make the changes that you did to test the changes.

Then copy-paste what is printed in the terminal window as a comment here.

Thx

Also, can you make sure that you don't have multiply installations: remove any `deb` installation and any global installation you may have.

Finally remember that it may take up to 30 seconds to update the config file

**Comment by Lukas-Schillinger** [comment]
I'm very confused now. 

I reinstalled on the same machine and tried installing on a laptop but couldn't recreate the issue. Everything is working as intended. Going through your instructions I can't find anything I had done differently when the error occurred. 

Doing the following could not recreate the error: 

- keeping the configurator tab open after installing
- keeping the config file open in an editor while using configurator
- modifying the config file with the vscode json formatter

I apologize for the false alarm. Thank you for trying to help me and thank you for sharing this extension!

**Comment by bassmanitram** [comment]
Lol... No problem Lukas. That happens to me all the time on other projects!

Thank you for using the extension and for being engaged with respect to feedback.

(May I suggest you use the deb distribution now - it's easier than the make install).

**Comment by bassmanitram** [comment]
Lol... No problem Lukas. That happens to me all the time on other projects!

Thank you for using the extension and for being engaged with respect to
feedback.

(May I suggest you use the deb distribution now - it's easier than the make
install... Though if you want the latest version you'll need to wait a day
or so since the current latest deb does not include the 'Path patterns'
feature).

All the best

Martin
